---
- hosts: all
  become: yes

  tasks:
    - name: Install apache
      apt:
        name:
          - apache2
          #- httpd-devel
        state: present
    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf.httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf
    - name: Makse sure apache is started
      service: name=apache2 state=started enabled=yes