---
- hosts: all
  become: true

  pre_tasks:
    - name: update apt cache
      apt: update_cahce=true cache_valid_time=4800

  tasks:
    - name: install java
      apt: name=openjdk-17-jdk state=present

    - name: download solr
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/\
              {{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: expand solr
      unarchive: 
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: run solr installation script
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_servie.sh
        {{download_dir}}/solr-{{solr_version}}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{solr_dir}}/din/solr

    - name: ensure solr is started and enabled on boot
      service: name=solr state=started enabled=yes

      